import { Router } from 'express';
import { guruRouter } from './gurus.js';
import { meRouter } from './me.js';
import { signalRouter } from './signals.js';
import { adminOpsRouter } from './pipeline.js';
import { flagRouter } from './flags.js';
import { adminJobsRouter } from './scheduler.js';
import { billingRouter } from './billing.js';
import { adminRouter } from './admin.js';
import { leaderboardRouter } from './leaderboard.js';
import { convergenceRouter } from './convergence.js';
import { portfolioRouter } from './portfolio.js';
import { heatmapRouter } from './heatmap.js';
import { watchlistRouter } from './watchlist.js';
import { priceAlertRouter } from './price-alerts.js';
import { exportRouter } from './export.js';
import { compareRouter } from './compare.js';
import { sectorRouter } from './sectors.js';
import { shareRouter } from './share.js';
import { backtestRouter } from './backtest.js';
import { performanceRouter } from './performance.js';
import { moodRouter } from './mood.js';
import { notificationRouter } from './notifications.js';
import { searchRouter } from './search.js';
import { earningsRouter } from './earnings.js';
import { correlationRouter } from './correlation.js';
import { weeklyReportRouter } from './weekly-report.js';
import { smartMoneyRouter } from './smart-money.js';

export const v1Router = Router();

v1Router.get('/', (_req, res) => {
  res.json({ api: 'firasa', version: 'v1' });
});

v1Router.use('/gurus', guruRouter);
v1Router.use('/me', meRouter);
v1Router.use('/signals', signalRouter);
v1Router.use('/admin', adminOpsRouter);
v1Router.use('/admin/jobs', adminJobsRouter);
v1Router.use('/flags', flagRouter);
v1Router.use('/billing', billingRouter);
v1Router.use('/admin/monitor', adminRouter);
v1Router.use('/leaderboard', leaderboardRouter);
v1Router.use('/convergence', convergenceRouter);
v1Router.use('/portfolio', portfolioRouter);
v1Router.use('/heatmap', heatmapRouter);
v1Router.use('/watchlist', watchlistRouter);
v1Router.use('/alerts', priceAlertRouter);
v1Router.use('/export', exportRouter);
v1Router.use('/sectors', sectorRouter);
v1Router.use('/compare', compareRouter);
v1Router.use('/share', shareRouter);
v1Router.use('/backtest', backtestRouter);
v1Router.use('/search', searchRouter);
v1Router.use('/notifications', notificationRouter);
v1Router.use('/performance', performanceRouter);
v1Router.use('/mood', moodRouter);
v1Router.use('/weekly-report', weeklyReportRouter);
v1Router.use('/earnings', earningsRouter);
v1Router.use('/correlation', correlationRouter);
v1Router.use('/smart-money', smartMoneyRouter);
