/** Tier feature limits — all capped, no Infinity (prevents abuse) */
export const TIER_LIMITS = {
  free: {
    maxGurus: 3,
    maxAlertsPerDay: 5,
    maxPriceAlerts: 5,
    maxApiCallsPerMin: 20,
    maxApiCallsPerDay: 500,
    maxSignalFetches: 50,       // signal list requests per day
    historyDays: 7,
    whatsapp: false,
    tradeTracker: false,
    apiAccess: false,
    customScoring: false,
    portfolio: false,
    watchlist: true,
    maxWatchlistItems: 50,
    maxConcurrentSessions: 2,
  },
  pro: {
    maxGurus: 20,
    maxAlertsPerDay: 50,
    maxPriceAlerts: 20,
    maxApiCallsPerMin: 60,
    maxApiCallsPerDay: 5_000,
    maxSignalFetches: 500,
    historyDays: 90,
    whatsapp: true,
    tradeTracker: true,
    apiAccess: false,
    customScoring: false,
    portfolio: false,
    watchlist: true,
    maxWatchlistItems: 200,
    maxConcurrentSessions: 5,
  },
  premium: {
    maxGurus: 100,
    maxAlertsPerDay: 200,
    maxPriceAlerts: 50,
    maxApiCallsPerMin: 120,
    maxApiCallsPerDay: 50_000,
    maxSignalFetches: 5_000,
    historyDays: 365,
    whatsapp: true,
    tradeTracker: true,
    apiAccess: true,
    customScoring: true,
    portfolio: true,
    watchlist: true,
    maxWatchlistItems: 200,
    maxConcurrentSessions: 10,
  },
  admin: {
    maxGurus: 10_000,
    maxAlertsPerDay: 10_000,
    maxPriceAlerts: 500,
    maxApiCallsPerMin: 300,
    maxApiCallsPerDay: 100_000,
    maxSignalFetches: 100_000,
    historyDays: 3650,
    whatsapp: true,
    tradeTracker: true,
    apiAccess: true,
    customScoring: true,
    portfolio: true,
    watchlist: true,
    maxWatchlistItems: 200,
    maxConcurrentSessions: 50,
  },
} as const;

export type TierLimits = (typeof TIER_LIMITS)[keyof typeof TIER_LIMITS];
